<a href="https://colab.research.google.com/github/DawidK4/MyNotebooks/blob/main/Eigenvectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Zad 1

In [ ]:
import numpy as np

v = np.array([1, 2, 3])
norm_v = np.linalg.norm(v)

u = v / norm_v

print("Wektor jednostkowy:", u)
print("Długość wektora jednostkowego:", np.linalg.norm(u))

Wektor jednostkowy: [0.26726124 0.53452248 0.80178373]
Długość wektora jednostkowego: 1.0


Zad 2

In [ ]:
M = np.array([[3, 2], [2, 6]])

eigenvalues, eigenvectors = np.linalg.eig(M)

eigenvectors_unit = eigenvectors / np.linalg.norm(eigenvectors, axis=0)

print("Wartości własne:", eigenvalues)
print("Jednostkowe wektory własne:\n", eigenvectors_unit)

Wartości własne: [2. 7.]
Jednostkowe wektory własne:
 [[-0.89442719 -0.4472136 ]
 [ 0.4472136  -0.89442719]]


Zad 3

In [ ]:
x0 = np.array([1, 1], dtype=float)

x = x0 / np.linalg.norm(x0)

# 1st iteration
x_next = np.dot(M, x)
x_next = x_next / np.linalg.norm(x_next)

# 2nd
x_next2 = np.dot(M, x_next)
x_next2 = x_next2 / np.linalg.norm(x_next2)

lambda_approx = np.dot(x_next2, np.dot(M, x_next2))

lambda_true = max(eigenvalues)
error = abs(lambda_true - lambda_aprox)

print("Wektor własny po 2 iteracjach:", x_next2)
print("Przybliżona wartość własna:", lambda_approx)
print("Błąd:", error)

Wektor własny po 2 iteracjach: [0.47137727 0.88193167]
Przybliżona wartość własna: 6.996300578034681
Błąd: 0.0036994219653188054


Zad 4

In [ ]:
from sympy import symbols, det, Matrix

a, b, c, d, e, f, l = symbols('a b c d e f lambda')

A = Matrix([
    [a - l, b, c],
    [b, d - l, e],
    [c, e, f - l]
])

determinant = A.det()
print("Wyznacznik:\n", determinant)

Wyznacznik:
 a*d*f - a*d*lambda - a*e**2 - a*f*lambda + a*lambda**2 - b**2*f + b**2*lambda + 2*b*c*e - c**2*d + c**2*lambda - d*f*lambda + d*lambda**2 + e**2*lambda + f*lambda**2 - lambda**3


Zad 5

In [ ]:
import numpy as np

# a) Wymiary MTM i MMT
M = np.array([[1, 1], [2, 4], [3, 9], [4, 16]])
MTM = np.dot(M.T, M)
MMT = np.dot(M, M.T)

print("Wymiary MTM:", MTM.shape)
print("Wymiary MMT:", MMT.shape)

# b) Elementy MTM i MMT
print("\nMTM:\n", MTM)
print("\nMMT:\n", MMT)

# Obserwacja:
# Macierze MTM i MMT mają różne wymiary i wartości.
# Kolejność mnożenia macierzy ma znaczenie.

# c) Wektor własny i wartość własna dla MMT
eigenvalues_MMT, eigenvectors_MMT = np.linalg.eig(MMT)

# Wybieramy dominującą wartość własną i wektor własny
dominant_eigenvalue_MMT = np.max(eigenvalues_MMT)
dominant_eigenvector_MMT = eigenvectors_MMT[:, np.argmax(eigenvalues_MMT)]

print("\nDominująca wartość własna MMT:", dominant_eigenvalue_MMT)
print("\nDominujący wektor własny MMT:", dominant_eigenvector_MMT)

Wymiary MTM: (2, 2)
Wymiary MMT: (4, 4)

MTM:
 [[ 30 100]
 [100 354]]

MMT:
 [[  2   6  12  20]
 [  6  20  42  72]
 [ 12  42  90 156]
 [ 20  72 156 272]]

Dominująca wartość własna MMT: 382.37857022259624

Dominujący wektor własny MMT: [-0.06315773 -0.22470839 -0.484652   -0.84298854]


Zad 6
a) Dowód:

Jeżeli v jest wektorem własnym MMT, to MMTv = λv. Mnożąc obie strony przez MT, otrzymujemy: MTMMTv = MTλv, co można zapisać jako (MTM)(MTv) = λ(MTv). To pokazuje, że MTv jest wektorem własnym MTM z tą samą wartością własną λ. Analogicznie można udowodnić, że jeżeli u jest wektorem własnym MTM, to Mu jest wektorem własnym MMT.

b) Wektor własny dla MTM:

In [ ]:
dominant_eigenvector_MTM = np.dot(M.T, dominant_eigenvector_MMT)

print("\nDominujący wektor własny MTM:", dominant_eigenvector_MTM)


Dominujący wektor własny MTM: [ -5.33848467 -18.81167594]


Zad 7
Dowód:

(MMT)T = (MT)TMT = MMT

(MTM)T = MT(MT)T = MTM

Transpozycja macierzy MMT i MTM jest równa samej macierzy, co oznacza, że są one symetryczne.

Zad 8

In [ ]:
A = np.array([[1, 1, 1], [1, 2, 3], [1, 3, 5]])

# a) Wektory i wartości własne
eigenvalues, eigenvectors = np.linalg.eig(A)

print("\nWartości własne:", eigenvalues)
print("\nWektory własne:\n", eigenvectors)

# b) Uporządkowanie wektorów
sorted_indices = np.argsort(eigenvalues)[::-1]  # Indeksy posortowane malejąco
sorted_eigenvalues = eigenvalues[sorted_indices]
sorted_eigenvectors = eigenvectors[:, sorted_indices]

print("\nPosortowane wartości własne:", sorted_eigenvalues)
print("\nPosortowane wektory własne:\n", sorted_eigenvectors)

# c) Procent wariancji
total_variance = np.sum(sorted_eigenvalues)
variance_v1 = sorted_eigenvalues[0] / total_variance * 100
variance_v1_v2 = (sorted_eigenvalues[0] + sorted_eigenvalues[1]) / total_variance * 100

print("\nProcent wariancji pokryty przez v1:", variance_v1)
print("\nProcent wariancji pokryty przez v1 i v2:", variance_v1_v2)


Wartości własne: [ 7.16227766e+00  8.37722340e-01 -2.95796566e-16]

Wektory własne:
 [[-0.21848175 -0.88634026  0.40824829]
 [-0.52160897 -0.24750235 -0.81649658]
 [-0.8247362   0.39133557  0.40824829]]

Posortowane wartości własne: [ 7.16227766e+00  8.37722340e-01 -2.95796566e-16]

Posortowane wektory własne:
 [[-0.21848175 -0.88634026  0.40824829]
 [-0.52160897 -0.24750235 -0.81649658]
 [-0.8247362   0.39133557  0.40824829]]

Procent wariancji pokryty przez v1: 89.52847075210475

Procent wariancji pokryty przez v1 i v2: 100.0
