<a href="https://colab.research.google.com/github/DawidK4/MyNotebooks/blob/main/PyTorchPocketReferenceSummary.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import torch
import torchvision
import numpy as np

# Tensors

In [25]:
device = "cuda" if torch.cuda.is_available() else "cpu"

x = torch.tensor([[1,2,3],[4,5,6]],
                 device=device)
y = torch.tensor([[7,8,9],[10,11,12]],
                 device=device)
z = x + y
print(z)

print(z.size())

print(z.device)

tensor([[ 8, 10, 12],
        [14, 16, 18]])
torch.Size([2, 3])
cpu


Moving tensors between CPUs and GPUs

In [26]:
device = "cuda" if torch.cuda.is_available() else "cpu"

x = x.to(device)
y = y.to(device)
z = x + y
z = z.to("cpu")

Creating tensors

In [27]:
#import torch # This is likely already imported in a previous cell
#import numpy as np # This is likely already imported in a previous cell

w = torch.tensor([1,2,3])
w = torch.tensor((1,2,3))
w = torch.tensor(np.array([1,2,3]))

w = torch.empty(100,200)
w = torch.zeros(100,200)
w = torch.ones(100,20)

# Creates a 100 × 200 tensor with elements from a uniform distribution on the interval [0, 1).
w = torch.rand(100,200)
# Elements are random numbers from a normal distribution with a mean of 0 and a variance of 1.
w = torch.randn(100,200)
# Elements are random integers between 5 and 10.
w = torch.randint(5,10,(100,200))

# Changed device to "cpu"
w = torch.empty((100,200), dtype=torch.float64, device="cpu")

x = torch.empty_like(w)

Data types

In [28]:
# Specify the data type at creation using dtype
w = torch.tensor([1,2,3], dtype=torch.float32)

# Use the casting method to cast to a new data type
w.int()       # w remains a float32 after the cast
w = w.int()   # w changes to an int32 after the cast

# Use the to() method to cast to a new type
w = w.to(torch.float64)
w = w.to(dtype=torch.float64)

# Python automatically converts data types during operations
x = torch.tensor([1,2,3], dtype=torch.int32)
y = torch.tensor([1,2,3], dtype=torch.float32)
z = x + y
print(z.dtype)

torch.float32


Tensor operations

In [29]:
x = torch.tensor([[1,2],[3,4],[5,6],[7,8]])
print(x)

# Indexing, returns a tensor
print(x[1,1])

# Indexing, returns a value as a Python number
print(x[1,1].item())

# Slicing
print(x[:2,1])

# Boolean indexing
# Only keep elements less than 5
print(x[x<5])

# Transpose array; x.t() or x.T can be used
print(x.t())

# Change shape; usually view() is preferred over
# reshape()
print(x.view((2,4)))

# Combining tensors
y = torch.stack((x, x))
print(y)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor(4)
4
tensor([2, 4])
tensor([1, 2, 3, 4])
tensor([[1, 3, 5, 7],
        [2, 4, 6, 8]])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
tensor([[[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]],

        [[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]])


# Deep learning devlopement

Data loading

In [30]:
from torchvision.datasets import CIFAR10

train_data = CIFAR10(root="./train/",
                     train=True,
                     download=True)

Data transforms

In [31]:
from torchvision import transforms

train_transforms = transforms.Compose([
  transforms.RandomCrop(32, padding=4),
  transforms.RandomHorizontalFlip(),
  transforms.ToTensor(),
  transforms.Normalize(
      mean=(0.4914, 0.4822, 0.4465),
      std=(0.2023, 0.1994, 0.2010))])

train_data = CIFAR10(root="./train/",
                     train=True,
                     download=True,
                     transform=train_transforms)

test_transforms = transforms.Compose([
  transforms.ToTensor(),
  transforms.Normalize(
      (0.4914, 0.4822, 0.4465),
      (0.2023, 0.1994, 0.2010))])

test_data = torchvision.datasets.CIFAR10(
      root="./test/",
      train=False,
      transform=test_transforms,
      # Added download=True to download the test dataset
      download=True)

100%|██████████| 170M/170M [00:02<00:00, 71.9MB/s]


Data batching

Sending data in batches not only allows more efficient training but also takes advantage of the parallel nature of GPUs to accelerate training.

In [32]:
trainloader = torch.utils.data.DataLoader(
                    train_data,
                    batch_size=16,
                    shuffle=True)

data_batch, labels_batch = next(iter(trainloader))
print(data_batch.size())
print(labels_batch.size())


testloader = torch.utils.data.DataLoader(
                    test_data,
                    batch_size=16,
                    shuffle=False)

data_batch, labels_batch = next(iter(testloader))
print(data_batch.size())
print(labels_batch.size())

torch.Size([16, 3, 32, 32])
torch.Size([16])
torch.Size([16, 3, 32, 32])
torch.Size([16])
